services:
  - type: web
    name: skillstack-backend
    env: python
    region: oregon

    rootDir: skillstack-backend  

    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000

    envVars:
      - key: PYTHON_VERSION
        value: 3.10

      - key: DATABASE_URL
        value: sqlite:///./skillstack.db
